### Owner: Kirill Borisov
### 
### The pipeline is currently under development
### and can only be fully implemented when we have a machine to run the project
### 
### The pipeline includes sample jobs for E2E tests and a skeleton for build.

stages:
  - dependencies
  - run
  - test

image: python:3.11-slim-bullseye

# node-install:
#     stage: dependencies
#     script:
#         - apt-get install -y ca-certificates curl gnupg
#         - mkdir -p /etc/apt/keyrings
#         - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
#         - NODE_MAJOR=20
#         - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
#         - apt-get update
#         - apt-get install nodejs -y
#         - cd ./Frontend
#         - npm install --prefer-offline
#         - cd ..
#     cache:
#         key:
#             files:
#                 - package.json
#         paths:
#             - node_modules

robot-install:
    stage: dependencies
    before_script:
        - apt-get update
        - apt-get -y install wget unzip
    script:
        - pip install robotframework
        - pip install robotframework-seleniumlibrary


# fe-run-job:       # This job runs in the build stage, which runs first.
#   stage: run
#   needs: ["node-install"]
#   script:
#       - ng serve

e2e-test:
    stage: test
    needs: ["robot-install"]
    before_script:
        - wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/win64/chromedriver-win64.zip
        - mkdir -p ~/.local/bin
        - unzip chromedriver-linux64.zip -d ~/.local/bin
        - mv ~/.local/bin/chromedriver-linux64/chromedriver  ~/.local/bin/chromedriver
        - chmod +x ~/.local/bin/chromedriver
    script:
        - robot Tests/ui/home.robot