### Owner: Kirill Borisov
### 
### The pipeline is currently under development
### and can only be fully implemented when we have a machine to run the project
### 
### The pipeline includes sample jobs for E2E tests and a skeleton for build.

stages:
  - dependencies
  - run
  - test

e2e-test:
  image: python:3.11.7-bullseye
  stage: test
  script:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-stable
    - apt-get install -y chromium-chromedriver
    - pip install -r Tests/requirements.txt
    #- python Tests/chromedriver_download.py
    #- mkdir -p ~/.local/bin
    #- mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
    #- chmod +x /usr/bin/chromedriver
    - chromedriver --version
    - robot -d results Tests/ui/home.robot
  artifacts:
    paths:
      - results