### Owner: Kirill Borisov
###
### The pipeline includes sample jobs for E2E tests and a skeleton for build.

stages:
  - build
  - test

fe-build:
  image: debian:stable
  stage: build
  before_script:
    - apt-get update
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh borisov@boriso02.stud.fim.uni-passau.de 'cd aspd/team2; eval $(ssh-agent); ssh-add ~/.ssh/id_rsa; git pull origin main'

e2e-test:
  image: ppandiyan/robotframework    # this is outdated, but i really couldn't care less at this point
  stage: test
  script:
    - robot -d results Tests/ui/home.robot
  artifacts:
    paths:
      - results