### Owner: Kirill Borisov
###
### The pipeline includes sample jobs for E2E tests and a skeleton for build.

stages:
  - build
  - test

fe-build:
  image: debian:stable
  stage: build
  script:
    - apt-get update
    - apt-get install -y sshpass
    - sshpass -e ssh -v -tt borisov@boriso02.stud.fim.uni-passau.de
    - cd aspd/
    - git pull origin main

e2e-test:
  image: ppandiyan/robotframework    # this is outdated, but i really couldn't care less at this point
  stage: test
  script:
    - robot -d results Tests/ui/home.robot
  artifacts:
    paths:
      - results