ocr:
  passport-analysis-file-path: "OCR/PassportAnalitics.py"
  certificate-of-enrollment-analysis-file-path: "OCR/ImmatrikulationAnalitics.py"
  health-insurance-certificate-analysis-file-path: "OCR/Health_Analitics.py"
  financial-document-analysis-file-path: "OCR/WorkContract.py"