package com.example.appforauslenderamt.entity;

public enum GainfulEmploymentType {
    HIGHLY_QUALIFIED_PERSON,
    ICT_CART,
    MOBILE_ICT_CARD,
    SHORT_TERM_MOBILITY_OF_INTERNALLY_TRANSFERRED_WORKERS,
    QUALIFIED_EMPLOYMENT_WITH_VOCATIONAL_TRAINING,
    QUALIFIED_EMPLOYMENT_WITH_ACADEMIC_TRAINING,
    UNQUALIFIED_EMPLOYMENT,
    SELF_EMPLOYED,
    RESEARCH,
    SHORT_TERM_MOBILITY_FOR_RESEARCHERS,
    IN_OTHER_MEMBER_STATE_AS_INTERNATIONALLY_PROTECTED_RESEARCHER,
    FOR_QUALIFIED_TOLERATED_PERSONS_FOR_PURPOSE_OF_EMPLOYMENT,
    FOR_HOLDERS_OF_TRAINING_ALLOWANCES_FOR_EMPLOYMENT_AFTER_COMPLETING_THEIR_TRAINING
}
