package com.example.appforauslenderamt.entity;

public enum JobSeekingType {
    AFTER_COMPLETING_STUDIES, AFTER_IN_COMPANY_TRAINING, AFTER_SCHOOL_TRAINING,
    TO_RECOGNISE_QUALIFICATION_ACQUIRED_ABROAD, AFTER_RECOGNITION_OF_QUALIFICATION_ACQUIRED_ABROAD,
    FOR_HOLDERS_OF_UNIVERSITY_DEGREE, AFTER_RESEARCH
}
