package com.example.appforauslenderamt.entity;

public enum SpecialResidenceRightsType {
    RIGHT_TO_RETURN, RESIDENCE_TITLE_FOR_FORMER_GERMANS,
    RESIDENCE_PERMIT_FOR_SOMEONE_ENTITLED_TO_LONG_TERM_RESIDENCE_IN_OTHER_EU_MEMBER_STATES
}
