package com.example.appforauslenderamt.entity;

public enum TrainingTypes {
    STUDIES, SCHOOL_ATTENDANCE, STUDY_APPLICANT, PASSING_AN_APPROVAL_TEST, LANGUAGE_COURSE_WITHOUT_STUDIES,
    SCHOOL_TRAINING, IN_COMPANY_TRAINING
}
